version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    working_dir: "/work/go-testing-sandbox"
    volumes:
      - ".:/work/go-testing-sandbox"
      - "go-pkg:/go/pkg/mod/cache"
    ports:
      - "5000:5000"

volumes:
  go-pkg:
