version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.2
    working_directory: /go/src/github.com/karakaram/go-testing-sandbox
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
